
DROP TABLE IF EXISTS login_info;
CREATE TABLE IF NOT EXISTS  login_info(
	user_id serial primary key,
	user_name varchar(50) unique not null,
	pass_word varchar(50) not null,
	first_name varchar(50) not null,
	last_name varchar(50) not null,
	created_on timestamp not null
);

/*
* login_info table:
* user_name - Player-made username
* pass_word - Player-made password
* first_name - Player-made first name
* last_name - Player-made last name
* created_on - Date and time of creation (using NOW() on populate to get current date and time)
*/
INSERT INTO login_info(user_name, pass_word, first_name, last_name, created_on)
VALUES('JaccoBouw','qxe','Jacco','Bouw', NOW()),
('RyanFisher','qxe','Ryan','Fisher',NOW()),
('AriiSharma','qxe','Arii','Sharma',NOW()),
('MitchellChapman','qxe','Mitchell','Chapman',NOW()),
('NickSietsema','qxe','Nick','Sietsema',NOW()),
('ChadLenth','qxe','Chad','Lenth',NOW())
;

/*
* leader_board table:
* user_name - Player-made username
* wins - The number of times the user has guessed the correct answer
* games_played - The number of times the user has played
* points - Points are accumulated when the player guesses correctly
		 - Player gets 1 point for easy, 3 points for medium, 5 points for hard
* score - Generated column that equals points if games_played = 0
		- If games-played > 0, = win ratio times points
*/

DROP TABLE IF EXISTS leader_board;
CREATE TABLE IF NOT EXISTS leader_board(
	user_name text,
	wins integer,
	games_played integer,
	points integer,
	score integer GENERATED ALWAYS AS (
		CASE
			WHEN games_played = 0 THEN points
			ELSE (((1.0 * wins) / (1.0 * games_played)) * points)
		END
	)STORED,
	easy_ans integer not null,
	med_ans integer not null,
	hard_ans integer not null
);

/*
* leader_board table:
* user_name - Player-made username
* user_id - User id generated by the database
* wins - Number of winsa
* games_played - Number of games played
* points - Number of points
*/
INSERT INTO leader_board(user_name, wins, games_played, points, easy_ans, med_ans, hard_ans)
VALUES('MitchellChapman',0,0,0,0,0,0),
('RyanFisher',0,0,0,0,0,0),
('JaccoBouw',0,0,0,0,0,0),
('AriiSharma',0,0,0,0,0,0),
('NickSietsema',0,0,0,0,0,0),
('ChadLenth',0,0,0,0,0,0)
;
