
DROP TABLE IF EXISTS login_info;
CREATE TABLE IF NOT EXISTS  login_info(
	user_id serial primary key,
	user_name varchar(50) unique not null,
	pass_word varchar(50) not null,
	first_name varchar(50) not null,
	last_name varchar(50) not null,
	created_on timestamp not null
);

/*
* login_info table:
* user_name - Player-made username
* pass_word - Player-made password
* first_name - Player-made first name
* last_name - Player-made last name
* created_on - Date and time of creation (using NOW() on populate to get current date and time)
*/
INSERT INTO login_info(user_name, pass_word, first_name, last_name, created_on)
VALUES('JaccoBouw','pwd','Jacco','Bouw', NOW()), /* User id: 1*/
('RyanFisher','pwd','Ryan','Fisher',NOW()),		 /* id: 2 */
('AriiSharma','pwd','Arii','Sharma',NOW()),
('MitchellChapman','pwd','Mitchell','Chapman',NOW()),
('NickSietsema','pwd','Nick','Sietsema',NOW()),
('ChadLenth','pwd','Chad','Lenth',NOW())
;

DROP TABLE IF EXISTS leader_board;
CREATE TABLE IF NOT EXISTS leader_board(
	user_name text,
	user_id serial primary key,
	wins integer,
	games_played integer,
	points integer,
	score integer GENERATED ALWAYS AS (
		CASE
			WHEN games_played = 0 THEN points
			ELSE (wins / games_played) * points 
		END
	)STORED
);

/*
* leader_board table:
* user_name - Player-made username
* user_id - User id generated by the database
* wins - Number of wins
* games_played - Number of games played
* points - Number of points
*/
INSERT INTO leader_board(user_name, user_id, wins, games_played, points)
VALUES('MitchellChapman',1,1,1,100),
('RyanFisher',2,1,1,200),
('JaccoBouw',3,1,1,300),
('AriiSharma',4,1,1,400),
('NickSietsema',5,0,0,0),
('ChadLenth',6,1,1,600)
;
